---
prometheus:
  enabled: true
  alertmanager:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  server:
    extraFlags:
      - "web.enable-otlp-receiver" # https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1462 and https://prometheus.io/docs/guides/opentelemetry/
    global:
      scrape_interval: 5s
      scrape_timeout: 3s
      evaluation_interval: 30s
    prometheus.yml:
      otlp:
        keep_identifying_resource_attributes: true
        promote_resource_attributes:
          - service.instance.id
          - service.name
          - service.namespace
          - cloud.availability_zone
          - cloud.region
          - container.name
          - deployment.environment.name
          - k8s.cluster.name
          - k8s.container.name
          - k8s.cronjob.name
          - k8s.daemonset.name
          - k8s.deployment.name
          - k8s.job.name
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.replicaset.name
          - k8s.statefulset.name
    persistentVolume:
      enabled: false
    service:
      servicePort: 9090
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "infra-otelcol"
          honor_labels: true
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                own_namespace: true

env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector-contrib"
  enabled: true
  nameOverride: otelcol
  mode: deployment
  presets:
    kubernetesAttributes:
      enabled: true
  service:
    type: ClusterIP
  ports:
    metrics:
      enabled: true
    prometheus:
      enabled: false
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "{{ .Release.Name }}-prometheus-server:9090"
        tls:
          insecure: true
    service:
      pipelines:
        metrics:
          exporters: [debug,otlp]
          processors: [batch]
          receivers: [otlp]
