services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:z
    ports:
      - "9090:9090"
  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.115.1
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './config.yaml:/otel-collector-config.yaml:z'
    ports:
      - "4317:4317"
      - "8888:8888"
